#Joseph ELsisi jre3wjh
#Lab 108
#Dec 1
OFILES = traveling.cpp middleearth.cpp
CXXFLAGS	= -Wall -g -std=c++11 -O2
.SUFFIXES: .o .cpp
.SUFFIXES: .o .s
main:	$(OFILES)
	$(CXX) $(CXXFLAGS) $(OFILES)
	doxygen
clean:
		/bin/rm -f *.o *~
